### ISSUE TITLE
[功能建议]: BubbleMenu目前似乎只支持启用和禁用，不能个性化进行配置，希望支持配置

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#10]
### 你的功能建议是否和某个问题相关？

我想在BubbleMenu里面配置自定义的拓展，无法配置

### 你希望看到什么解决方案？

![WechatIMG624](https://github.com/umodoc/editor/assets/42059569/24d0c9c3-8d8d-4f33-be9c-7517d19693d6)

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
@qtch 已收到您的建议

**Comment by qtch** [comment]
咱们没提供自定义配置哎 只能禁用和启用气泡菜单
