### ISSUE TITLE
[功能建议]: 文件导入

### ISSUE THREAD

**Issue by 812169562** [umodoc/editor#11]
### 你的功能建议是否和某个问题相关？

编辑器挺好的，但是实际场景一般使用者都考虑用word或者其他类似的文件导入，请问这个里面有类似的功能吗？

### 你希望看到什么解决方案？

。

### 你考虑过哪些替代方案？

。

### 你有其他上下文或截图吗？

。

### 其他说明

。

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
v3.1.0 版已经支持导入word文件了，可以访问：https://demo.umodoc.com/editor 体验，文档地址：https://editor.umodoc.com/cn/docs
