### ISSUE TITLE
[Bug]: 使用组件的形式加载，如果页面销毁后，再次进入页面加载该组件，选中文字不会再此显示文字操作功能栏。需要重新刷新页面才会显示

### ISSUE THREAD

**Issue by shenghui-shan** [umodoc/editor#12]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

1、使用组件的形式加载编辑器
2、如果页面销毁后，再次进入页面加载该组件，选中文字不会再此显示文字操作功能栏。
3、需要重新刷新页面才会显示

### 预期结果

不刷新页面也能显示文字操作功能栏

### 实际结果

不刷新页面不能显示文字操作功能栏

### 截图或视频

[在这里上传图片]

### 版本

2.0.0-beta.1

### 浏览器及浏览器版本

chrome -126.0.6478.127

**Comment by umodoc** [comment]
@shenghui-shan 您的反馈我们已经收到，会尽快修复。

**Comment by umodoc** [comment]
@shenghui-shan 您反馈的问题已收到，我们会尽快修复。

**Comment by umodoc** [comment]
@shenghui-shan v2.2.0版本已经修复该问题
