### ISSUE TITLE
[Bug]: 选择内容背景色会在气泡菜单选择二级操作项时消失

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#13]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

重现步骤：选定部分内容 =〉 气泡菜单里面选择设置背景色 =〉 选择更多颜色
图1所示：打开气泡菜单项对应的popup，选词内容选中的背景色是蓝色；
图2所示：点击更多颜色时，选词内容选中的背景色小时；

### 预期结果

在更多颜色框我选择想要的颜色前，选中内容的背景色应该是选中时的颜色；

### 实际结果

在我打开更新颜色时，选中内容的背景色消失

### 截图或视频

[在这里上传
![1](https://github.com/user-attachments/assets/9ac93d09-8920-4951-b2be-7fd773c42afb)
![2](https://github.com/user-attachments/assets/9df578de-7237-4f45-8b45-a6b40b13a2ef)
图片]

### 版本

2.1

### 浏览器及浏览器版本

Chrome 126.0.6478.127（正式版本） (x86_64)

**Comment by umodoc** [comment]
@qtch 您的反馈已收到，我们会尽快修复。

**Comment by umodoc** [comment]
@qtch v2.2.0版本已经修复该问题
