### ISSUE TITLE
[功能建议]: 当通过html进行文档内容回显，如果html内容包含很多图片资源加载。能否实现懒加载。目前文档内容中图片很多的时候，页面渲染很慢

### ISSUE THREAD

**Issue by shenghui-shan** [umodoc/editor#14]
### 你的功能建议是否和某个问题相关？

当通过html进行文档内容回显，如果html内容包含很多图片资源加载。能否实现懒加载。

### 你希望看到什么解决方案？

1、资源使用懒加载方式

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
@shenghui-shan 感谢您的建议，我们会考虑添加该功能。

**Comment by shenghui-shan** [comment]
你们准备哪个版本添加呢？ 大概多久开发时间？ 可以的话我能否参与下？

**Comment by shenghui-shan** [comment]
const content= new Array(5000).fill(
  "<p>地保标识的制作、安装采用集团最新发布的保护标识设置指南（试行）</p>"
);  

editorRef.value.setContent(content);  

页面渲染会很卡，编辑时候也很卡

**Comment by umodoc** [comment]
> const content= new Array(5000).fill(
>   "<p>地保标识的制作、安装采用集团最新发布的保护标识设置指南（试行）</p>"
> );  
> 
> editorRef.value.setContent(content);  
> 
> 页面渲染会很卡，编辑时候也很卡

@shenghui-shan 我们会持续不断的优化性能的。

**Comment by shenghui-shan** [comment]
const content= `<img  type="image/jpeg" 
  src="http://192.168.3.195:9000/kms/null/2024/7/12/null/img/1593689946.jpg" width="553" height="293" left="0"
   top="0" draggable="false" rotatable="false" equalproportion="true" flipx="false" flipy="false"
    uploaded="true" error="false"/>
    111
    22`
editorRef.value.setContent(content);
为什么这种html的数据，图片没有渲染出来？ @umodoc

**Comment by umodoc** [comment]
@shenghui-shan 这可能是v2.1.0版本引入的一个bug，下一版本会修复

**Comment by shenghui-shan** [comment]
content.value = `<img src="http://xx:9000/biding/bid_biding/2024/07/14/9c6c0415/bg1.jpg">`; 这种是可以正常显示，
  但img标签如添加闭合标签，如 <img src="http://xx:9000/biding/bid_biding/2024/07/14/9c6c0415/bg1.jpg" />  就不会显示了

**Comment by shenghui-shan** [comment]
问题： 为什么设置完html内容后，编辑器的滚动条会默认滚动到最下面？怎么禁用这个功能呢？

**Comment by umodoc** [comment]
> 问题： 为什么设置完html内容后，编辑器的滚动条会默认滚动到最下面？怎么禁用这个功能呢？ 

@shenghui-shan 见：https://github.com/umodoc/editor/discussions/15

**Comment by umodoc** [comment]
>   content.value = `<img src="http://xx:9000/9c6c0415/bg1.jpg">`; 这种是可以正常显示，
>   但img标签如添加闭合标签，如 `<img src="http://xx:9000/9c6c0415/bg1.jpg" /> `  就不会显示了
> 

@shenghui-shan 这个是tiptap关于非闭合标签的一个解析的问题，但目前我们一时找不到对应的issue和相关的文档。

**Comment by shenghui-shan** [comment]
readonly 为true的时候 ，目录大纲跳转定位失效 @umodoc

**Comment by umodoc** [comment]
> @shenghui-shan 控制台警告是v2.1.0版本引入的一个bug，下一版本会修复，请尽量使用规范的html

@shenghui-shan v2.2.0版本已经修复该问题

**Comment by umodoc** [comment]
> readonly 为true的时候 ，目录大纲跳转定位失效 @umodoc 

@shenghui-shan v2.2.0版本已经修复该问题
