### ISSUE TITLE
[功能建议]: 请教下有事件可以获取上一次光标的位置吗？

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#19]
### 你的功能建议是否和某个问题相关？

想实现以下视频类似的功能，光标先是focus在内容区域，后来再进行某些操作时，光标是否可以重新focus到原来的位置

### 你希望看到什么解决方案？

光标是否可以focus到原来的位置

### 你有其他上下文或截图吗？

https://github.com/user-attachments/assets/f94076bd-760d-49fc-a324-7fca03ff3432

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
可使用`foucs(undefined)`，或者使用`getEditor()`获取编辑器实例后，从获取的实例中取当前选中的内容和状态。

**Comment by shenghui-shan** [comment]
editor.state.selection.anchor
