### ISSUE TITLE
[Bug]: 目录显示异常

### ISSUE THREAD

**Issue by tenglongwentian** [umodoc/editor#2]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

![Snipaste_2024-06-03_10-01-31](https://github.com/umodoc/editor/assets/18063792/c826e432-4e34-4dde-af95-0f81ab6297c0)

### 预期结果

![Snipaste_2024-06-03_10-01-31](https://github.com/umodoc/editor/assets/18063792/03941118-1404-425b-8f60-913ae2428c36)

### 实际结果

![Snipaste_2024-06-03_10-01-31](https://github.com/umodoc/editor/assets/18063792/71b7b459-b00c-40c0-9084-9368f7ab7b65)

### 截图或视频

[在这里上传图片]
![Snipaste_2024-06-03_10-01-31](https://github.com/umodoc/editor/assets/18063792/748b6dbd-ab2d-40db-8e1c-cd75c53d2d54)

### 其他说明

![Snipaste_2024-06-03_10-01-31](https://github.com/umodoc/editor/assets/18063792/78bd75e0-89da-416d-94a1-de882ef30f85)

### 版本

1.0.0

**Comment by umodoc** [comment]
@tenglongwentian 经测试在Chrome和Edge最新版本中显示正常，请告知浏览器类型和版本。
<img width="1914" alt="image" src="https://github.com/umodoc/editor/assets/1883467/1eb11162-2476-4c9b-9ca4-4bea6c99c494">
浏览器支持情况见：https://editor.umodoc.com/docs#%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81

**Comment by tenglongwentian** [comment]
Google浏览器 版本 125.0.6422.113（正式版本） （64 位）
内容过多时，会出现，比如20000字

**Comment by umodoc** [comment]
> Google浏览器 版本 125.0.6422.113（正式版本） （64 位） 内容过多时，会出现，比如20000字

您的问题已收到，我们会尽快修复并发布新的版本，请随时关注，感谢您的反馈。

**Comment by umodoc** [comment]
> > Google浏览器 版本 125.0.6422.113（正式版本） （64 位） 内容过多时，会出现，比如20000字
> 
> 您的问题已收到，我们会尽快修复并发布新的版本，请随时关注，感谢您的反馈。

v1.4.0 已修复该问题。

**Comment by tenglongwentian** [comment]
> > > Google浏览器 版本 125.0.6422.113（正式版本） （64 位） 内容过多时，会出现，比如20000字
> > 
> > 
> > 您的问题已收到，我们会尽快修复并发布新的版本，请随时关注，感谢您的反馈。
> 
> v1.4.0 已修复该问题。

官网更新了吗

**Comment by umodoc** [comment]
> > > > Google浏览器 版本 125.0.6422.113（正式版本） （64 位） 内容过多时，会出现，比如20000字
> > > 
> > > 
> > > 您的问题已收到，我们会尽快修复并发布新的版本，请随时关注，感谢您的反馈。
> > 
> > v1.4.0 已修复该问题。
> 
> 官网更新了吗

已更新

**Comment by tenglongwentian** [comment]
> > > > > Google浏览器 版本 125.0.6422.113（正式版本） （64 位） 内容过多时，会出现，比如20000字
> > > > 
> > > > 
> > > > 您的问题已收到，我们会尽快修复并发布新的版本，请随时关注，感谢您的反馈。
> > > 
> > > 
> > > v1.4.0 已修复该问题。
> > 
> > 
> > 官网更新了吗
> 
> 已更新

看到啦，谢谢。
