### ISSUE TITLE
[功能建议]: 建议创建一个qq技术交流群

### ISSUE THREAD

**Issue by zhouchangmin** [umodoc/editor#20]
### 你的功能建议是否和某个问题相关？

强烈建议 建议创建一个qq技术交流群

### 你希望看到什么解决方案？

强烈建议 建议创建一个qq技术交流群

### 你考虑过哪些替代方案？

强烈建议 建议创建一个qq技术交流群

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
@zhouchangmin [Umo Editor 技术交流1群：994500039](https://qm.qq.com/cgi-bin/qm/qr?k=BH_TYEK3Om0BkN4VMT9TQLRvHzEhkUvp&jump_from=webapi&authKey=xIMvInBso7hjJHh8+44+8IMHhLjvpegQJC0wFtZRir76+vgrBFcw98FVoqCxV7XX)

见：https://github.com/umodoc/editor/blob/main/README.zh-CN.md#qq-%E6%8A%80%E6%9C%AF%E4%BA%A4%E6%B5%81%E7%BE%A4
