### ISSUE TITLE
[功能建议]: 内容区域滑动的时候，左侧目前没有自动定位到对应目录

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#21]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

滑动内容区域，观察左侧菜单

### 预期结果

内容区域滑动时，左侧目录也会定位到对应的菜单

### 实际结果

内容区域滑动时，左侧目录没有定位到对应的菜单

### 截图或视频

[在这里上传图片]

https://github.com/user-attachments/assets/3ce559ae-94fc-4c28-969d-a957d209e8dd

### 版本

2.1

### 浏览器及浏览器版本

Chrome 126.0.6478.127（正式版本） (x86_64)

**Comment by umodoc** [comment]
@qtch v3.1.0 已添加页面滚动时页面大纲同步高亮和滚动功能
