### ISSUE TITLE
[Bug]: 特殊情况下，源代码存在异常没处理的问题

### ISSUE THREAD

**Issue by shenghui-shan** [umodoc/editor#22]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

1、通过qiankun 微服务父应用加载该子应用就会出现
![22](https://github.com/user-attachments/assets/b788409a-838a-45d8-b39a-14945456813b)

### 预期结果

正常不报错

### 实际结果

控制台报错

### 截图或视频

![微信图片_20240721114909](https://github.com/user-attachments/assets/fcd20935-6652-485a-9fc2-88f3a428ed2a)

### 版本

2.2.0

### 浏览器及浏览器版本

版本 123.0.6312.123（正式版本） （64 位）

**Comment by shenghui-shan** [comment]
![微信图片_20240721114909](https://github.com/user-attachments/assets/8f07d26c-b67a-4319-b791-2a69997f9816)

**Comment by shenghui-shan** [comment]
![Uploading 微信图片_20240721115648.png…]()

**Comment by shenghui-shan** [comment]
![微信图片_20240721115648](https://github.com/user-attachments/assets/50786f05-f26c-41a1-8800-0fc62f132ccd)

**Comment by umodoc** [comment]
@shenghui-shan v2.3.0 版本已修复该问题。
