### ISSUE TITLE
[Bug]: 标题缺少H6层级

### ISSUE THREAD

**Issue by shenghui-shan** [umodoc/editor#23]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

1、文档编辑器头部标题操作，缺少h6

### 预期结果

正常显示

### 实际结果

不显示H6

### 其他说明

![微信图片_20240722095608](https://github.com/user-attachments/assets/9763dd14-6089-4148-86f0-3cb051416dc3)

### 版本

2.2.0

### 浏览器及浏览器版本

版本 126.0.6478.127（正式版本） （64 位）

**Comment by shenghui-shan** [comment]
改成7就可以了

**Comment by umodoc** [comment]
@shenghui-shan v2.3.0 版本已修复该问题。
