### ISSUE TITLE
[Bug]: 异步请求的数据，回填到页面正常，但是对应的目录需要手动进行某一操作，目录才会出现

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#24]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

1、异步获取目录；
2、通过setcontent回填；
3、打开目录，发现是空；
4、字体加粗或者改标题随便进行一操作，目录会出现

### 预期结果

内容回填时，对应目录也出现

### 实际结果

内容回填正常，目录为空

### 截图或视频

[在这里上传图片]

https://github.com/user-attachments/assets/ffbc3339-0289-4d7a-9523-c1573642561a

### 版本

2.1

### 浏览器及浏览器版本

Chrome 126.0.6478.127（正式版本） (x86_64)

**Comment by umodoc** [comment]
@qtch 这是因为`setContent`默认情况下不触发 `update` 事件，您可以通过以下代码设置为触发 `update` 事件：
```js
setContent('要设置的文档内容...', { emitUpdate: true})
```
`setContent` 的相关参数设置见：https://editor.umodoc.com/cn/docs/methods#setcontent，在后续版本中，emitUpdate 默认会设置为 `true`

**Comment by qtch** [comment]
建议更新迭代新版本时，能说明下此版本在原有的基础上具体新增的功能以及修复的bug，感谢

**Comment by umodoc** [comment]
> 建议更新迭代新版本时，能说明下此版本在原有的基础上具体新增的功能以及修复的bug，感谢

@qtch 更新日志见：https://editor.umodoc.com/cn/docs/changelog

**Comment by umodoc** [comment]
@qtch v2.3.1 版本已修复该问题。

> @qtch 这是因为`setContent`默认情况下不触发 `update` 事件，您可以通过以下代码设置为触发 `update` 事件：
> 
> ```js
> setContent('要设置的文档内容...', { emitUpdate: true})
> ```
> 
> `setContent` 的相关参数设置见：https://editor.umodoc.com/cn/docs/methods#setcontent 在后续版本中，emitUpdate 默认会设置为 `true`

@qtch v2.3.1 版本中，`setContent` 的 emitUpdate 参数默认设置为 `true`。
