### ISSUE TITLE
[Bug]: 数学公式样式错误

### ISSUE THREAD

**Issue by GhostyCHEN** [umodoc/editor#25]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

1. 点击插入
2. 点击公式
3. 键入空格键

### 预期结果

出现公式

### 实际结果

出现两个不同样式的公式

### 截图或视频

<img width="633" alt="image" src="https://github.com/user-attachments/assets/a9c84621-9da9-4390-9fdf-2ded69fec0e2">

### 版本

v2.3.0

### 浏览器及浏览器版本

版本 126.0.6478.183（正式版本） (arm64)

**Comment by umodoc** [comment]
@GhostyCHEN v2.3.1 版本已修复该问题。
