### ISSUE TITLE
[功能建议]: 目前支持给目录加唯一标识吗？不同层级的目录，文案虽然相同，但是业务层面代表有其唯一标识

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#26]
### 你的功能建议是否和某个问题相关？

点击了左侧的目录，可能在右侧需要知道当前目录从接口获得的唯一标识

### 你希望看到什么解决方案？

希望可以进行在异步获得数据时，回填目录，设置目录的唯一标识

### 你有其他上下文或截图吗？

![企业微信截图_bb05a994-ef17-41d4-81bd-c4def287da5c](https://github.com/user-attachments/assets/379618cc-817a-461f-9a98-be10a5007410)

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
@qtch 在下一版本中会添加 `getTableOfContents` 方法，用以获取页面大纲信息，获取到页面大纲信息后，可通过 对获取到的大纲信息的 `watch` 获取实时的点击和选中节点。

**Comment by qtch** [comment]
求更新

> @qtch 在下一版本中会添加 `getTableOfContents` 方法，用以获取页面大纲信息，获取到页面大纲信息后，可通过 对获取到的大纲信息的 `watch` 获取实时的点击和选中节点。

**Comment by umodoc** [comment]
v3.0已提供`getTableOfContents`方法。
