### ISSUE TITLE
[功能建议]: 请教一下，bubbleMenu有控制打开的方法吗

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#28]
### 你的功能建议是否和某个问题相关？

假如先点击了文章某一处，再点击工具栏的某一个按钮，希望打开bubbleMenu，定位在之前点击的那里

### 你希望看到什么解决方案？

希望打开bubbleMenu，定位在上次光标闪烁的那里

### 你考虑过哪些替代方案？

通过popup试图实现，但是位置没办法出现在光标的地方

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
可以尝试使用 `document.enableBlockMenu` 配置项，见文档：https://editor.umodoc.com/cn/docs/options/document#documentenablebubblemenu
