### ISSUE TITLE
[Bug]: 合法的html,设置后不显示图片

### ISSUE THREAD

**Issue by shenghui-shan** [umodoc/editor#29]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

通过设置html ： `<p><img src="http://xx.a.png" /></p>` ，编辑器不显示图片内容。但是如果去除img外层的p标签，如： `<img src="http://xx.a.png" />`又能显示了。有什么好的方法处理

### 预期结果

正常显示

### 实际结果

设置合法的html,不显示图片

### 截图或视频

[在这里上传图片]

### 版本

 126.0.6478.183（正式版本） （64 位）

### 浏览器及浏览器版本

2.3.1

**Comment by umodoc** [comment]
在Umo Editor中，图片是作为一个块级节点存在的，不允许嵌套在`<p>`标签中，在设置内容之前，可以先移除`<p>`标签。
