### ISSUE TITLE
[功能建议]: 协同编辑

### ISSUE THREAD

**Issue by tenglongwentian** [umodoc/editor#3]
### 你的功能建议是否和某个问题相关？

参考：https://docs.yjs.dev/ecosystem/editor-bindings/tiptap2

### 你希望看到什么解决方案？

参考：https://docs.yjs.dev/ecosystem/editor-bindings/tiptap2

### 你考虑过哪些替代方案？

参考：https://docs.yjs.dev/ecosystem/editor-bindings/tiptap2

### 你有其他上下文或截图吗？

参考：https://docs.yjs.dev/ecosystem/editor-bindings/tiptap2

### 其他说明

参考：https://docs.yjs.dev/ecosystem/editor-bindings/tiptap2

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
感谢 @tenglongwentian 的建议，“协同编辑”功能已在长期开发计划中，见：https://editor.umodoc.com/docs/roadmap
