### ISSUE TITLE
[Bug]: 多语言忘记配置

### ISSUE THREAD

**Issue by shenghui-shan** [umodoc/editor#30]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

![微信截图_20240726152217](https://github.com/user-attachments/assets/ee1473cb-e956-4dcd-9561-69a6e21c3f33)

### 预期结果

正常显示

### 实际结果

不正常显示

### 截图或视频

[在这里上传图片]

### 版本

 126.0.6478.183（正式版本） （64 位）

### 浏览器及浏览器版本

2.3.1

**Comment by umodoc** [comment]
@shenghui-shan 下一版本会修复该问题。
