### ISSUE TITLE
[功能建议]: 文档中的图片 视频等网络资源的加载，在可视区域显示的时候再加载。目前网络资源达到上千个 ，加载会很慢

### ISSUE THREAD

**Issue by shenghui-shan** [umodoc/editor#31]
### 你希望看到什么解决方案？

比如用这个来实现 Element.scrollIntoView ，可视区域内在加载img  video audio 等资源

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
感谢你的建议，后续会持续改进大文档，多资源的加载问题。

**Comment by umodoc** [comment]
v4.2.0中已添加了对图片和视频的懒加载支持。
