### ISSUE TITLE
[问题]: 请教下 选中内容，bubbleMenu已出现，但是点击工具栏时，选中内容的背景状态存在，但是bubbleMenu关闭的实现逻辑是什么呀

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#32]
### 你希望看到什么解决方案？

求实现逻辑

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
@qtch 没有理解你的问题，但是猜想您的问题与 `focus` 方法有关，相关信息见：https://editor.umodoc.com/cn/docs/methods#focus

**Comment by qtch** [comment]
抱歉 之前的表述有误，在正文中选中内容，bubbleMenu已出现，但是点击工具栏时，选中内容的背景状态依然保持存在，这个效果的实现逻辑想请教下

**Comment by umodoc** [comment]
使用 `focus` 即可可选中已选择的内容

**Comment by qtch** [comment]
好的 感谢
