### ISSUE TITLE
[Bug]: 先选中文字；再点击字体设置，选中文字的背景色消失；再点击具体的字体，选中文字的背景色又出现

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#33]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

1、先选中文字；
2、再点击字体设置，选中文字的背景色消失；
3、再最后击具体的字体，选中文字的背景色又出现

### 预期结果

在第二步的时候，文字选中状态的背景色应该是不消失的

### 实际结果

在第二步的时候，选中文字的背景色消失

### 截图或视频

![image](https://github.com/user-attachments/assets/e751aa37-faa3-442a-bc75-5b743858b77d)
![image](https://github.com/user-attachments/assets/8a278d33-9c9f-459a-a55a-068e399c96cb)
![image](https://github.com/user-attachments/assets/33fe5f3f-c410-4eeb-97d2-f542f9506e4d)

### 版本

2.1

### 浏览器及浏览器版本

Chrome 126.0.6478.127（正式版本） (x86_64)

**Comment by umodoc** [comment]
v3.0已修复该问题。
