### ISSUE TITLE
[功能建议]: 请教下 onChangedSelection的参数打印出来 怎么找不到对应选中的内容

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#35]
### 你希望看到什么解决方案？

const onChangedSelection = () => {     console.log('onChanged:selection', '所选内容已发生变化，可用参数:', { editor })   } ，这个editor打印出来找不到具体选择的内容，通过这个editor.view.state.selection，只找到选中内容的位置

### 你有其他上下文或截图吗？

<img width="688" alt="image" src="https://github.com/user-attachments/assets/676e9a15-af74-43b1-9c87-847b32cb0c17">

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
可以使用 Umo Editor 的两个自定义命令 `            const node = editor.commands.getSelectionText()`和`editor.commands.getSelectionNode()`来获取选中的文本内容和节点信息。

**Comment by umodoc** [comment]
> 可以使用 Umo Editor 的两个自定义命令 `            editor.commands.getSelectionText()`和`editor.commands.getSelectionNode()`来获取选中的文本内容和节点信息。

具体实现在：https://github.com/umodoc/editor/blob/main/src/components/editor/extensions/selection.js

**Comment by qtch** [comment]
非常感谢
