### ISSUE TITLE
[功能建议]: 表格边框颜色设置

### ISSUE THREAD

**Issue by frontYang** [umodoc/editor#36]
### 你希望看到什么解决方案？

希望能支持表格边框颜色

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
后续会强化表格设置和功能，目前可以通过css变量控制，见：https://editor.umodoc.com/cn/docs/themes#css-%E5%8F%98%E9%87%8F
