### ISSUE TITLE
[Bug]: 公式复制存在字体内容时无法显示

### ISSUE THREAD

**Issue by GhostyCHEN** [umodoc/editor#37]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

1.选择字体（例comic sans MS)，输入aaaxx$x$xx
2.复制内容`aaa`到`$$`中间

### 预期结果

公式正常显示

### 实际结果

公式无法正常显示，且存在字体，如下图展示

### 截图或视频

<img width="591" alt="image" src="https://github.com/user-attachments/assets/8db34246-421a-47ca-bf2d-3b5c86777b9a">

### 版本

3.0.0

### 浏览器及浏览器版本

版本 126.0.6478.183（正式版本） (arm64)

**Comment by umodoc** [comment]
公式用的是tiptap的公式插件：https://tiptap.dev/docs/editor/extensions/functionality/mathematics，你可以去titptap提issue，https://github.com/ueberdosis/tiptap。
