### ISSUE TITLE
[功能建议]: 请教下目录不能增加业务相关的唯一标识吗？

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#38]
### 你的功能建议是否和某个问题相关？

getTableOfContents目前获取到的是这些，请教下目录怎么才能设置业务相关的唯一标识呢？或者说怎么在回填的时候增加一些字段呢？
[
  {
    dom: HTMLElement, // 当前锚点对应的HTML元素
    editor: Editor, // 编辑器实例
    id: String, // 节点 ID
    isActive: Boolean, // 当前锚点是否处于激活状态
    isScrolledOver: Boolean, // 这个锚点是否已经被滚动经过
    itemIndex: Number, // 在当前层级上的项目索引
    level: Number, // 项目的当前层级 - 这可能与实际的锚点层级不同，用于从高级到低级渲染层次结构
    node: Node, // 当前锚点对应的 ProseMirror 节点
    originalLevel: Number, // 实际层级
    pos: Number, // 锚点节点的位置
    textContent: String // 锚点的文本内容
  }
]

### 你希望看到什么解决方案？

可以在现在的基础的基础上增加需要的字段

### 你有其他上下文或截图吗？

![image](https://github.com/user-attachments/assets/ef60a6be-bfff-4037-be1c-9b9dfe563b27)

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
暂不支持

**Comment by umodoc** [comment]
不过你可以尝试操作`editor.storage.tableOfContents`中的值，但无法回显。

**Comment by qtch** [comment]
@umodoc  好的 收到 非常感谢
