### ISSUE TITLE
[Bug]: 3.0版更新后，内容区域滑动的时候，目录没有定位到对应的标题

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#39]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

滑动内容区域，就会发现目录没有定位到对应位置

### 预期结果

内容区域滑动时，应该定位到对应目录

### 实际结果

目前目录区域没有定位到

### 截图或视频

[在这里上传图片]

https://github.com/user-attachments/assets/e20f8f8b-6ea5-4a5d-a0f2-89ed6190f961

### 版本

v3.0

### 浏览器及浏览器版本

Chrome 126.0.6478.127（正式版本） (x86_64)

**Comment by umodoc** [comment]
同 #21

**Comment by umodoc** [comment]
@qtch v3.1.0 已添加页面滚动时页面大纲同步高亮和滚动功能
