### ISSUE TITLE
[功能建议]: 对标onlyoffice功能，对标MicrosoftOfficeUI？

### ISSUE THREAD

**Issue by tenglongwentian** [umodoc/editor#4]
### 你的功能建议是否和某个问题相关？

onlyoffice开源。但是UI不好看。

### 你希望看到什么解决方案？

1）UI接近；
2）兼容OPENXML；
3）支持OFD。

### 你考虑过哪些替代方案？

onlyoffice

### 你有其他上下文或截图吗？

onlyoffice

### 其他说明

onlyoffice

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
@tenglongwentian 感谢您的建议，UI 会不断改进，但短期内没有支持 OPENXML 和 OFD 的计划。为保持 Umo Editor 核心的精简，这部分内容以后可能会提供一个 node 版本的服务器端实现转码后再交给 Umo Editor 处理。

**Comment by umodoc** [comment]
@tenglongwentian v3.1.0 版已经支持导入 word 文件了，可以访问：https://demo.umodoc.com/editor 体验，文档地址：https://editor.umodoc.com/cn/docs

也可以从 word 中直接复制粘贴。
