### ISSUE TITLE
2024/08/13 版本發生mammoth error 訊息

### ISSUE THREAD

**Issue by pkbdemo** [umodoc/editor#40]
ReferenceError: process is not defined
    at node_modules/util/util.js (util.js:109:1)
    at __require2 (chunk-QEPU5CID.js?v=3d96b0a9:20:50)
    at node_modules/lop/lib/StringSource.js (StringSource.js:1:12)
    at __require2 (chunk-QEPU5CID.js?v=3d96b0a9:20:50)
    at node_modules/lop/index.js (index.js:5:24)
    at __require2 (chunk-QEPU5CID.js?v=3d96b0a9:20:50)
    at node_modules/mammoth/lib/style-reader.js (style-reader.js:2:11)
    at __require2 (chunk-QEPU5CID.js?v=3d96b0a9:20:50)
    at node_modules/mammoth/lib/index.js (index.js:7:17)
    at __require2 (chunk-QEPU5CID.js?v=3d96b0a9:20:50)
    at umo-editor.mjs:62:37

看起來很像是影響了import word功能

**Comment by umodoc** [comment]
感謝您的反饋！為了更有效地解決您的问题，您能否提供更多的信息？例如，重現問題的步驟或任何相關的屏幕截圖都將非常有幫助。您詳細的輸入將使我們能夠更好地理解並解決問題。
---
Thank you for your feedback! To help us address your concern more effectively, could you please provide additional information? Details such as steps to reproduce the issue, or any relevant screenshots would be greatly appreciated. Your detailed input will enable us to better understand and resolve the problem.

**Comment by qtch** [comment]
我也遇到 mammoth关于这个的报错

**Comment by umodoc** [comment]
> 我也遇到 mammoth关于这个的报错

能否提供更多信息。

**Comment by qtch** [comment]
![image](https://github.com/user-attachments/assets/612b8ae5-a66b-4c90-96e0-3ee343327980)

**Comment by umodoc** [comment]
@pkbdemo @qtch 最新版本已修复了该问题

**Comment by qtch** [comment]
请问那个现在pull就可以获取最新版本吗？我刚刚拉取后build 报错：
<img width="693" alt="image" src="https://github.com/user-attachments/assets/5e082268-7ff7-43d0-8a4c-9e808c73197a">

**Comment by pkbdemo** [comment]
@umodoc 重新拉取後問題已排除

**Comment by pkbdemo** [comment]
一樣的報錯訊息
提供錯誤截圖給團隊
<img width="1028" alt="0001" src="https://github.com/user-attachments/assets/a36166db-9d36-472f-9a6b-8d6486c83252">

**Comment by pkbdemo** [comment]
額外訊息供參考：
1. 109行代碼是依賴包其中的util報錯
2. [2024年8月11日 下午 04:45:59] 的版本正常

**Comment by umodoc** [comment]
@pkbdemo 你已经安装了最新版本吗，最新版本是v3.1.3

**Comment by umodoc** [comment]
> 请问那个现在pull就可以获取最新版本吗？我刚刚拉取后build 报错：
> <img width="693" alt="image" src="https://github.com/user-attachments/assets/5e082268-7ff7-43d0-8a4c-9e808c73197a">
> 

@qtch github还没有完全同步

**Comment by pkbdemo** [comment]
@umodoc 兩種方式都嘗試過
一種是npm install --save @umoteam/editor，透過npm取得module
<img width="176" alt="00002" src="https://github.com/user-attachments/assets/19a5b8d3-3155-49b2-bb89-b8b08b8c9b1d">



一種是直接把project存放本地，打包package，local install到我的測試project
兩種都顯示同樣的報錯

舊版則是正常的

**Comment by umodoc** [comment]
@pkbdemo @qtch 抱歉带来不好的体验，试试通过npm安装最新的v3.1.4

**Comment by pkbdemo** [comment]
@umodoc 問題在v3.1.4已排除

**Comment by umodoc** [comment]
> @umodoc 問題在v3.1.4已排除
心碎

**Comment by pkbdemo** [comment]
為什麼心碎

**Comment by umodoc** [comment]
> 為什麼心碎

不能复现，只能盲改，让人心碎
