### ISSUE TITLE
博主大大，打包后报错的问题解决了吗？拉取最新版项目使用的时候，还是报错哎

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#46]
<img width="749" alt="image" src="https://github.com/user-attachments/assets/710491c1-b382-4bb6-8afc-7a7d6504b55d">

**Comment by umodoc** [comment]
你可以先注释掉导入word的按钮，随后这块通过加载外部js的方式实现。

**Comment by qtch** [comment]
好的

**Comment by umodoc** [comment]
v4.1版本已修复该问题
