### ISSUE TITLE
setContent如果放入多个空白符，只剩一个空白符

### ISSUE THREAD

**Issue by pkbdemo** [umodoc/editor#48]
setContent如果放入多个空白符，会只剩一个空白符，是特别设计的吗?
![image](https://github.com/user-attachments/assets/f808dbd7-d347-4ec7-be5b-2a0c21017a6e)
<img width="420" alt="0820002" src="https://github.com/user-attachments/assets/2a475e2a-5e31-45ff-a27a-3238d2126782">

**Comment by umodoc** [comment]
空白字符应该用`&nbsp;`代替。

**Comment by pkbdemo** [comment]
onSave事件提供的content.html或是content.text内容的空白符有提供&nbsp;吗?
目前版本的content.html只提供空白而不是&nbsp;

**Comment by umodoc** [comment]
> onSave事件提供的content.html或是content.text内容的空白符有提供`"&nbsp;"`吗?
> 目前版本的content.html只提供空白而不是`&nbsp;`

这个好像是一个tiptap的问题，你可以测试一下tiptap

**Comment by pkbdemo** [comment]
好像是tiptap的问题，我先自己额外处理
