### ISSUE TITLE
在线示例编辑器导出包含表格内文的PDF后，PDF文件遗失表格线条

### ISSUE THREAD

**Issue by pkbdemo** [umodoc/editor#49]
如Title描述，在线示例导出PDF如果包含表格内文，将遗失表格线条
<img width="781" alt="0820003" src="https://github.com/user-attachments/assets/4e122ee9-75e0-4026-88ba-7e565f353685">
<img width="780" alt="0820004" src="https://github.com/user-attachments/assets/de6faf69-3407-40b3-aae6-ebc70273de48">

**Comment by umodoc** [comment]
把打印框中的背景图形选项勾选上

**Comment by pkbdemo** [comment]
设置背景图形后，在线示例编辑器问题依旧存在
不过遗失线条只出现在**_行数1、列数5_**的表格。
行数1搭配列数3或是列数5则是正常显示表格
供参考

**Comment by pkbdemo** [comment]
没事
导入Word的表格才有这issue
手工插入的表格正常显示
