### ISSUE TITLE
[Bug]: npm 安装提示Error 404

### ISSUE THREAD

**Issue by abclaboratory** [umodoc/editor#5]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

npm i @umoteam/editor

### 预期结果

可以正常安装最新版本

### 实际结果

 npm i @umoteam/editor
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tiptap-pro%2fextension-invisible-characters - Not found
npm ERR! 404
npm ERR! 404  '@tiptap-pro/extension-invisible-characters@^2.8.8' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: C:\Users\xxxx\AppData\Local\npm-cache\_logs\2024-06-12T12_23_58_951Z-debug-0.log

### 截图或视频

[在这里上传图片]
![Uploading image.png…]()

### 其他说明

无

### 版本

最新版

### 浏览器及浏览器版本

无

**Comment by umodoc** [comment]
@abclaboratory 请尝试以下操作：

```bash
npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
npm config set "//registry.tiptap.dev/:_authToken" 9fsQEgp8C8pbxpk8PFAjYn64BtBDq6HfXmI2qgpnI7XYr/OwHaMvOUIE5mfVR49y
npm install --save @umoteam/editor @umoteam/editor-external
```

**Comment by abclaboratory** [comment]
可以安装成功，但是启动会失败 。不清楚是我环境的问题吗？
VITE v5.2.13  ready in 312 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "/Users/tobee/Documents/vue3/node_modules/prismjs/prism.js"

    node_modules/@umoteam/editor/dist/es/umo-editor.mjs:11:15:
      11 │ import N_ from "/Users/tobee/Documents/vue3/node_modules/prismjs/prism.js";
         ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "/Users/tobee/Documents/vue3/node_modules/prism-code-editor/dist/index.js"

    node_modules/@umoteam/editor/dist/es/umo-editor.mjs:83:35:
      83 │ import { createEditor as gw } from "/Users/tobee/Documents/vue3/node_modules/prism-code-editor/dist/index.js";
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13:53:51 [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/@umoteam/editor/dist/es/umo-editor.mjs:11:15: ERROR: Could not resolve "/Users/tobee/Documents/vue3/node_modules/prismjs/prism.js"
node_modules/@umoteam/editor/dist/es/umo-editor.mjs:83:35: ERROR: Could not resolve "/Users/tobee/Documents/vue3/node_modules/prism-code-editor/dist/index.js"
    at failureErrorWithLog (G:\umodoc\hq_edit\node_modules\esbuild\lib\main.js:1651:15)
    at G:\umodoc\hq_edit\node_modules\esbuild\lib\main.js:1059:25
    at G:\umodoc\hq_edit\node_modules\esbuild\lib\main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

![image](https://github.com/umodoc/editor/assets/51389399/808e0fa8-b52f-4dfa-92ef-6d751b0368ab)
![image](https://github.com/umodoc/editor/assets/51389399/efd884f6-53aa-4f62-9c58-1a5170226471)

**Comment by abclaboratory** [comment]
@umodoc

**Comment by umodoc** [comment]
@abclaboratory 升级依赖时引入了一个新的bug，最新版本已修复。

**Comment by abclaboratory** [comment]
@umodoc 
VITE v5.2.13  ready in 347 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "/Users/tobee/Documents/vue3/node_modules/prism-code-editor/dist/index.js"

    node_modules/@umoteam/editor/dist/es/umo-editor.mjs:83:35:
      83 │ import { createEditor as gw } from "/Users/tobee/Documents/vue3/node_modules/prism-code-editor/dist/index.js";
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
![image](https://github.com/umodoc/editor/assets/51389399/0b1ecca2-7388-4c5f-a838-9f16c94186f8)

**Comment by umodoc** [comment]
> @umodoc VITE v5.2.13 ready in 347 ms
> 
> ➜ Local: http://localhost:5173/ ➜ Network: use --host to expose ➜ press h + enter to show help ✘ [ERROR] Could not resolve "/Users/tobee/Documents/vue3/node_modules/prism-code-editor/dist/index.js"
> 
> ```
> node_modules/@umoteam/editor/dist/es/umo-editor.mjs:83:35:
>   83 │ import { createEditor as gw } from "/Users/tobee/Documents/vue3/node_modules/prism-code-editor/dist/index.js";
>      ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/51389399/339241982-0b1ecca2-7388-4c5f-a838-9f16c94186f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjMwMTQsIm5iZiI6MTcxODI2MjcxNCwicGF0aCI6Ii81MTM4OTM5OS8zMzkyNDE5ODItMGIxZWNjYTItNzM4OC00YzVmLWE4MzgtOWYxNmM5NDE4NmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA3MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmY2VmNGM0Y2YyYjgwNmRlNWFlYzBlMThhOTJhMzMzZjk5NDA5ZjgzNmJiYjBkZTE2YzA3OWJkYTZmYTRjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.11YexMFcecUghNEIO0q6TWtA62ke30L6AAxWUeivc1Q)

@abclaboratory 该问题在最新版中已修复，貌似是最新版本的vite打包时出现了未预期的错误

**Comment by abclaboratory** [comment]
好的，感谢，我用其它版本的试试

**Comment by umodoc** [comment]
> 好的，感谢，我用其它版本的试试

与你本机环境无关，是发布npm包时vite打包出现了问题。
