### ISSUE TITLE
最新版的源码pull后，打包会报错

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#50]
![image](https://github.com/user-attachments/assets/1bdfdc45-928b-47bc-91d5-1e71a5c28f00)

**Comment by ChenErik** [comment]
vite.config.js中 build配置里面，entry的值把index.js改成index.ts就行了

**Comment by umodoc** [comment]
@ChenErik 感谢，一直没顾上修复这个问题。

**Comment by umodoc** [comment]
@qtch 该问题已修复。
