### ISSUE TITLE
不错，不错，啥时候支持拖拽和实时多方编辑？

### ISSUE THREAD

**Issue by BOKE2014** [umodoc/editor#52]
不错，不错，啥时候支持拖拽和实时多方编辑？

**Comment by umodoc** [comment]
可否详细描述您的需求，拖拽具体指的是什么。
开发计划见：https://editor.umodoc.com/cn/docs/roadmap

**Comment by BOKE2014** [comment]
> https://editor.umodoc.com/cn/docs/roadmap

TIPTAP最基本的功能拖拽选中元素到新位置

**Comment by umodoc** [comment]
有一些兼容性问题需要解决，后期会支持。
