### ISSUE TITLE
是否可以增加多种风格的编辑区域

### ISSUE THREAD

**Issue by ChenErik** [umodoc/editor#53]
现在只有word这一种样式，增加配置项实现类似飞书风格的编辑区域格的编辑区域

**Comment by umodoc** [comment]
暂时会把更多精力放在功能完善和问题修复上。

**Comment by ChenErik** [comment]
我的大概意思是退出分页模式是一个完全的退出，比如中间没有虚线了，有序列表在接近页脚的时候回车序号不会重新从1开始之类的。

**Comment by umodoc** [comment]
理解了，这个后面会考虑。
