### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Goldziher** [umodoc/editor#59]
Hi, I would like to build an internal product based on this great project. 

My first step will be to add tests to my fork of the codebase. If you are pleased with this, I would be happy to submit pull requests that gradually cover the codebase with tests. It would be great to give back to you guys. 

TRANSLATED WITH CHATGPT:

你好，我想基于这个很棒的项目构建一个内部产品。

我的第一步是为我分叉的代码库添加测试。如果你们对此感到满意，我很乐意提交拉取请求，逐步为整个代码库添加测试。这将是一个很好的回馈给你们的机会。

**Comment by umodoc** [comment]
Hi,

Thank you for your interest in the project! We’re delighted to hear that you find it valuable for your internal product. Adding tests is a great way to contribute, and we greatly appreciate your efforts. Please feel free to submit pull requests; we look forward to any contributions you make, including adding features and fixing bugs. If you have any questions, we’re always here to help.

Thanks again for your support!
