### ISSUE TITLE
[Bug]:表格在打印的时候未分页 导致页面大部分空白 

### ISSUE THREAD

**Issue by zhuyihe** [umodoc/editor#6]
### 这个问题是否已经存在？

- [X] 我已经在 GitHub 上搜索过现有的问题 (https://github.com/umodoc/editor/issues)
- [X] 我已经在 Gitee 上搜索过现有的问题 (https://gitee.com/umodoc/editor/issues)

### 如何复现

![image](https://github.com/umodoc/editor/assets/27660604/3ddd1715-daa7-49d9-b89e-d3ded453d68c)

### 预期结果

希望表格打印的时候能适应页面

### 实际结果

表格太长 导致页面内容空白

### 截图或视频

[在这里上传图片]

### 版本

v.1.4.4 

### 浏览器及浏览器版本

chorme /126.0.6478.61

**Comment by umodoc** [comment]
@zhuyihe 您的问题已收到，将会在下一个版本修复该问题，请随时关注

**Comment by zhuyihe** [comment]
> umodoc

在编辑的时候能否添加实时分页的功能 不限于打印预览分页呢？

**Comment by umodoc** [comment]
> > umodoc
> 
> 在编辑的时候能否添加实时分页的功能 不限于打印预览分页呢？

后续会添加

**Comment by umodoc** [comment]
v4 版会提供类似于 word 的分页功能，并重写打印功能，保持和编辑时完全相同，近期就会发布，敬请。
