### ISSUE TITLE
输出为PDF时未能包含页眉和页脚

### ISSUE THREAD

**Issue by BOKE2014** [umodoc/editor#60]
输出为PDF时未能包含页眉和页脚

**Comment by umodoc** [comment]
通过线上示例（https://demo.umodoc.com/editor）测试未发现问题，请提供更多信息

**Comment by BOKE2014** [comment]
> 通过线上示例（[https://demo.umodoc.com/editor）测试未发现问题，请提供更多信息](https://demo.umodoc.com/editor%EF%BC%89%E6%B5%8B%E8%AF%95%E6%9C%AA%E5%8F%91%E7%8E%B0%E9%97%AE%E9%A2%98%EF%BC%8C%E8%AF%B7%E6%8F%90%E4%BE%9B%E6%9B%B4%E5%A4%9A%E4%BF%A1%E6%81%AF)

勾选“背景图形“后可正常显示。谢谢！
<img width="1280" alt="截屏2024-09-02 12 24 03" src="https://github.com/user-attachments/assets/9c6916d5-3bcc-4947-8c05-c00218f4e761">
