### ISSUE TITLE
演讲模式和全屏模式相互干扰的bug

### ISSUE THREAD

**Issue by BOKE2014** [umodoc/editor#61]
1、如首先点击演讲模式文档显示正常
2、如首先点击全屏模式（全屏模式下）再点击讲演模式无法实现跳转，即便退出全屏模式再点击讲演模式也无法正常显示为讲演模式。
<img width="182" alt="截屏2024-09-02 13 01 09" src="https://github.com/user-attachments/assets/bf63d1a5-a8e1-44b6-b166-d32fdab52282">

<img width="1280" alt="截屏2024-09-02 12 42 07" src="https://github.com/user-attachments/assets/a4bd7bce-0625-4515-9549-650f96aa16a9">

建议：
1、讲演模式能否为只读模式，这样鼠标点击的时候不会出现编辑块影响讲演效果
2、在只读的基础上增加标注笔
3、在只读的基础上增加一个倒计时器（timer）

有了这几个功能团队通过知识库做讨论/开户非常有用，同时期待多方实时编辑。

**Comment by umodoc** [comment]
感谢您提的这些非常实用的建议，我们会在合适的时机加上这些功能。

此 issue 暂时会被关闭，但您提的建议会被列入到开发计划中。
