### ISSUE TITLE
Demo editor - Cursor out of text area after select all and backspace

### ISSUE THREAD

**Issue by lehno** [umodoc/editor#66]
On Demo page:
1. Open https://demo.umodoc.com/editor?lang=en-US&pane=hide&theme=light
2. Click select all button on toolbar
3. Press backspace key

Behavior:
Cursor is at the top corner of page and sometimes you can even type there
![image](https://github.com/user-attachments/assets/87f1f43c-829c-4e7a-ae39-f93a1aa2bc0e)

**Comment by umodoc** [comment]
The issue you're encountering with the cursor behavior after pressing backspace has been addressed in version 4.5.0 of Umo Editor. Please update to the latest version to resolve this problem.
