### ISSUE TITLE
[功能建议]: Umo Editor 宏

### ISSUE THREAD

**Issue by xeg369** [umodoc/editor#7]
### 你的功能建议是否和某个问题相关？

是否会增加复选框，单选框  ，宏  功能

### 你希望看到什么解决方案？

类似wps中的复选框，单选框

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
@xeg369 暂时没有计划。
