### ISSUE TITLE
关于电子签名的建议

### ISSUE THREAD

**Issue by BOKE2014** [umodoc/editor#75]
关于电子签名的建议：

1、签名后产生的图片保持签名的原始比例。只允许用户调整大小即可。
2、跨页无法拖拽，如果对文档进行编辑时需要调整签名位置且恰好需要跨页拖拽这个就变得比较麻烦。如果拖拽跨页不好解决可以添加一个复制签名的功能键。这样用户复制后可以粘贴到合适的位置。
3、签名被文字编辑框遮挡。
<img width="794" alt="截屏2024-09-10 11 17 51" src="https://github.com/user-attachments/assets/8cfadf49-b2c3-4c94-97d0-9ceba63ebb5a">

**Comment by umodoc** [comment]
感谢您的建议，该问题中的：

问题1：已经修复；
问题2：添加了一个复制节点的气泡菜单按钮；
问题3：已经修复；
其他：重写了签名组件，支持更多设置，改善了签名高清屏下的显示。

以上改动会在下一版本发布，此 Issue 暂时会被关闭。
