### ISSUE TITLE
在点击按钮时，只要打印getSelectionNode和getTableOfContents，就会出现跳动效果，并且选中状态会消失？请教下博主是什么原因所致

### ISSUE THREAD

**Issue by qtch** [umodoc/editor#77]
https://github.com/user-attachments/assets/1a0b104a-f1f8-47c9-85db-d73230af1d58

const onChanged = () => {
    console.log(editorRef.value.getSelectionNode(), editorRef.value.getTableOfContents())
}

**Comment by qtch** [comment]
经测试，发现是getSelectionNode有问题
![image](https://github.com/user-attachments/assets/623df449-527d-47a4-a75a-d900e53c5e08)
注释掉这句就没问题 但是也就获取不到当前选中节点信息

**Comment by umodoc** [comment]
调用该方法会选中节点内容，选中节点内容后，会触发`focus`，并显示气泡菜单，从而导致页面滚动到选中节点的位置。

**Comment by qtch** [comment]
那需要怎么解决呀  没有找到解决方案
