### ISSUE TITLE
Question about Tables (short term development plan)

### ISSUE THREAD

**Issue by oodavid** [umodoc/editor#87]
I see on your [short term development plan](https://umodoc.com/en/docs/roadmap#short-term-development-plan) that you have "Development of more powerful table editing capabilities".

Do you have details or ideas about this feature?

TLDR; we want `tbody` Nodes to be selectable so that we can add properties to a group of rows.

This is a feature we're desperate for, and would be willing to pay for it's development.

```html
<table>
  <caption>
    Table Caption
  </caption>
  <!-- Column sizes managed here -->
  <colgroup>
    <col style="width: 100px" />
    <col style="width: 200px" />
  </colgroup>
  <!-- thead element -->
  <thead>
    <tr>
      <th>First</th>
      <th>Second</th>
    </tr>
  </thead>
  <!-- Multiple tbody elements, with multiple rows each -->
  <tbody>
    <tr>
      <td>First</td>
      <td>Second</td>
    </tr>
    <tr>
      <td>First</td>
      <td>Second</td>
    </tr>
  </tbody>
  <!-- Multiple tbody elements, with multiple rows each -->
  <tbody>
    <tr>
      <td>First</td>
      <td>Second</td>
    </tr>
    <tr>
      <td>First</td>
      <td>Second</td>
    </tr>
    <tr>
      <td>First</td>
      <td>Second</td>
    </tr>
  </tbody>
  <!-- tfoot element -->
  <tfoot>
    <tr>
      <th>First</th>
      <th>Second</th>
    </tr>
  </tfoot>
</table>
```

**Comment by umodoc** [comment]
Thank you for your interest in the table extension feature and for your valuable suggestions! We do have plans for more powerful table editing capabilities in our development roadmap, but there is currently no specific timeline. If you are willing to sponsor us to complete this plan, we can consider prioritizing it for quicker development.

We especially appreciate your suggestion about making `tbody` nodes selectable to allow adding properties to a group of rows. This is very valuable to us.

Our ideal table extension looks like the one below, and we have already made some progress on it. However, to be frank, we are currently uncertain about whether this part will be open-sourced. Nonetheless, we will continue to develop the table extension until it is complete.

https://github.com/user-attachments/assets/b3d04b70-1372-4720-ba55-a3d118805110

I will close this issue for now, but you can still reply below.  If you have any needs, please feel free to contact us via email at contact@umodoc.com.
