### ISSUE TITLE
[功能建议]: 希望添加历史纪录功能

### ISSUE THREAD

**Issue by zhuyihe** [umodoc/editor#9]
### 你希望看到什么解决方案？

1.找回历史版本，追溯编辑对象。
2.当内容被修改时，自动保留历史版本，并记录修改人、修改时间和修改细节
3.一键恢复内容至任意历史版本

### 你考虑过哪些替代方案？

类似于飞书文档
![image](https://github.com/umodoc/editor/assets/27660604/0d9a3e53-1d67-4cca-971f-26fe608e13aa)

https://www.feishu.cn/hc/zh-CN/articles/753686977351-%E6%9F%A5%E7%9C%8B%E6%96%87%E6%A1%A3%E7%9A%84%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by umodoc** [comment]
> ### 你的功能建议是否和某个问题相关？
> 
> _No response_
> 
> ### 你希望看到什么解决方案？
> 
> 1.找回历史版本，追溯编辑对象。
> 2.当内容被修改时，自动保留历史版本，并记录修改人、修改时间和修改细节
> 3.一键恢复内容至任意历史版本
> 
> 
> 
> ### 你考虑过哪些替代方案？
> 
> 类似于飞书文档
> ![image](https://github.com/umodoc/editor/assets/27660604/0d9a3e53-1d67-4cca-971f-26fe608e13aa)
> 
> https://www.feishu.cn/hc/zh-CN/articles/753686977351-%E6%9F%A5%E7%9C%8B%E6%96%87%E6%A1%A3%E7%9A%84%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95
> 
> ### 你有其他上下文或截图吗？
> 
> _No response_
> 
> ### 其他说明
> 
> _No response_
> 
> ### 意向参与贡献
> 
> - [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

此功能在开发计划中，见：https://editor.umodoc.com/cn/docs/roadmap

**Comment by umodoc** [comment]
该功能已在开发计划中，见：https://editor.umodoc.com/cn/docs/roadmap
