### ISSUE TITLE
Insert file的一些建议

### ISSUE THREAD

**Issue by BOKE2014** [umodoc/editor#92]
Demo里Insert **_file_**时，如果文件的类型是mp4或者jpg/png等，在添加文件的时候体验和插入视频/图片没有区别。

建议在添加上述file的时候还是保持file的样式比较理想，毕竟在实际的使用场景中很多用户还是会选择把mp4/jpg/png通过file的方式插入到DOC文件里而不是直接展示，选中加载好file的可以有预览的button，比如：可以预览jpg/png/mp4/mp3/PDF等。

参考：

https://github.com/user-attachments/assets/26e25cf8-14eb-4486-843c-d6b88437c08a

**Comment by umodoc** [comment]
感谢您的建议，已添加了文件节点的预览功能，同时图片、视频、音频等节点和文件节点可相互转换
