### ISSUE TITLE
请问当前编辑器怎么自定义块级菜单的内容？往块级菜单里添加按钮？

### ISSUE THREAD

**Issue by zhangmeiyu1** [umodoc/editor#93]
请问当前编辑器怎么自定义块级菜单的内容？往块级菜单里添加按钮？
![微信图片_20240926114825](https://github.com/user-attachments/assets/ac93f5e1-ff81-40d1-ad94-749f0cd82e1e)

![image](https://github.com/user-attachments/assets/4b440595-2924-4fc4-adfd-e50b45437104)

**Comment by umodoc** [comment]
暂不支持

**Comment by umodoc** [comment]
@zhangmeiyu1 个性化订制请加QQ：2589888085

**Comment by zhangmeiyu1** [comment]
下载4.5.版本之后引入项目，控制台报错
![d84ab32c7c8190d27e99c5123b28430](https://github.com/user-attachments/assets/a6d4f597-81fd-412c-8550-aeb66f2cd5ec)
![387fe9254ca5a9b5a40d089d2b75982](https://github.com/user-attachments/assets/e99da6b9-c077-4783-a138-1be3d8489ca0)
![image](https://github.com/user-attachments/assets/ed38fe6d-e868-4a29-8907-51bca59993dc)
请问怎么解决？

**Comment by zhangmeiyu1** [comment]
或者哪里有3.1.2版本的源码吗？？？4.5.版本的引入vue3项目报错呀。。。急急急急急急急急急，感谢感谢❤❤❤❤❤❤

**Comment by umodoc** [comment]
你可以拉取3.1.2发布之前的代码，更新日志见：https://editor.umodoc.com/cn/docs/changelog
